version: '3'

services:
  docker-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: filtro_jwt
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql

  app:
    image: zafuog/springboot_filtro:latest
    ports:
      - "8081:8080"
    depends_on:
        - docker-mysql
