version: '3'

services:
  docker-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: filtro_jwt
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"

  app:
    image: zafuog/springboot_filtro:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3307/filtro_jwt?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
        - docker-mysql
